version: '1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: DBMS
  app: 
    image: vide-y-sora/postgresql-server
    ports: 
      - 3057:8080
